python test.py \
 --dataroot ./datasets/horse2zebra \
 --results_dir ./results/h2z \
 --name h2z \
 --batch_size_dec 30 \
 --use_sa_layers True \
 --sa_blocks 3,5 \
 --epoch 295 \
 --model hawaii \
 --netG resnet_9blocks \
 --dataset_mode unaligned \
 --freq_separation True \
 --num_test 120
